[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements-demo.txt"

[deploy]
startCommand = "cd backend && python demo_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10